# use node_js as language flag
language: node_js

node_js:
  - '10'

script:
  - yarn run test
  - yarn run build
  - yarn run coverage
  # Upload to coveralls, but don't _fail_ if coveralls is down.
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local-dir: build
  on:
    branch: master
